### ISSUE TITLE
Resource created by the Helm construct ignore `disableResourceNameHashes`

### ISSUE THREAD

**Issue by iliapolo** [cdk8s-team/cdk8s-core#1106]
### Reproduction Steps:

This code:

```go
func main() {                                         
  app := cdk8s.NewApp(nil)                                             
  chart := cdk8s.NewChart(app, jsii.String("root"), &cdk8s.ChartProps {            
   DisableResourceNameHashes: jsii.Bool(true),                       
  })                                             
  cdk8s.NewHelm(chart, jsii.String("redis1"), &cdk8s.HelmProps{               
    Chart: jsii.String("bitnami/redis"),                          
  })                                             
  app.Synth()                                        
}
```

Still creates a resource with a hash:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: redis
    chart: redis-12.1.1
    heritage: Helm
    release: root-redis1-c82bf964
  name: root-redis1-c82bf964
  namespace: default
data:
  redis-password: Q0lHclBMaWRrag==
type: Opaque
```

### Error Log:

No error. Just unexpected output.

### Other

Note that when `ReleaseName` is specified, this doesn't happen and the release name is used instead. 
Could it be that helm itself generates names based on the release name? If so, the release name should consider the `disableResourceNameHashes`.

---

This is :bug: Bug Report
