### ISSUE TITLE
Add support to Deno

### ISSUE THREAD

**Issue by Alvise88** [cdk8s-team/cdk8s-core#481]
Even with the latest version of deno it doesn't seem possible to use cdk8s.

Deno: v1.21.3
```
import { Chart } from "https://esm.sh/cdk8s@2.2.85";
import {Construct} from "https://esm.sh/constructs@10.0.130";

class MyChart extends Chart {
  constructor(scope: Construct, ns: string) {
    super(scope, ns);

    // add contents here
  }
}

/**
 * hello-world.js
 */
function capitalize(word: string) {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function hello(name: string) {
  return "Hello " + capitalize(name);
}

console.log(hello("john"));
console.log(hello("Sarah"));
console.log(hello("kai"));

/**
 * Output:
 *
 * Hello John
 * Hello Sarah
 * Hello Kai
 */
```

```
deno --unstable run stack.ts
```

```
Uncaught SyntaxError: The requested module 'https://esm.sh/cdk8s@2.2.85' does not provide an export named 'Chart'
import { Chart } from "https://esm.sh/cdk8s@2.2.85";
```

**Comment by y12studio** [comment]
It seems like recent version already support cdk8s and cdk8s+.

```
docker run -i --entrypoint sh docker.io/denoland/deno:1.30.3 <<\EOF
deno run -A - <<\EOOF
import * as kplus from 'npm:cdk8s-plus-25'
import * as cdk8s from 'npm:cdk8s'
const app = new cdk8s.App()
const chart = new cdk8s.Chart(app, 'ch101')
const deploy203 = new kplus.Deployment(chart, 'd203', {
    replicas: 2,
    containers: [
        { 
            image: 'nginx', 
            securityContext: { ensureNonRoot: false, readOnlyRootFilesystem: false}
        }
    ],
})
new kplus.Service(chart, 'srv987', {
        selector: deploy203, 
        ports: [ { port: 80, targetPort: 8080}]
    });
console.log(app.synthYaml())
EOOF
EOF
```

output

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch101-d203-c886a9fd
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: ch101-d203-c8cfa8e5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: ch101-d203-c8cfa8e5
    spec:
      automountServiceAccountToken: false
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
---
apiVersion: v1
kind: Service
metadata:
  name: ch101-srv987-c8aad50a
spec:
  externalIPs: []
  ports:
    - port: 80
      targetPort: 8080
  selector:
    cdk8s.io/metadata.addr: ch101-d203-c8cfa8e5
  type: ClusterIP
```
